# language: node_js
# node_js:
#  - "node"

language : python
python :
  -"3.6"

sudo : required

services :
  docker

branches:
only:
 - master

before_script:
  - pip install selenium

script:
 - python tests/test.py
