dist: trusty
sudo: required

language: node_js
node_js:
  - "10"

services :
  - docker

cache:
    directories:
      - node_modules/

addons:
  apt:
    packages:
      - docker-ce
  sonarcloud:
    organization: "sonarcloud"

notifications:
  email: false

before_install:
  - sudo service postgresql stop
  - sudo docker-compose up -d
  - sleep 20
  - npm update
  - npm install puppeteer
  - npm install jasmine
  - npm install sonar-scanner@3.1.0

script:
  - curl localhost:3000
  - npm run test
  - sonar-scanner -Dsonar.projectKey=CdP-2018-1_4 -Dsonar.organization=myra282-github -Dsonar.sources=src/js/ -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=56b7844a6f61a6fe367a3785f676db6d12a7bef6
