dist: trusty
sudo: required

language: node_js
node_js:
  - "10"

services :
  - docker

cache: npm


addons:
  apt:
    packages:
      - docker-ce

notifications:
  email: false

before_install:
  - sudo docker-compose up -d
  - npm install puppeteer
  - npm install jasmine


script:
  - curl localhost:3000
  - npm run test
