dist: trusty
sudo: required

language: node_js
node_js:
- "10"

notifications:
  email: false

before_install:
  - npm install puppeteer
  - npm install jasmine

# services :
#   docker-compose up

script:
  - curl localhost:3000
  - yarn test
