dist: trusty
sudo: required

language: node_js
node_js:
  - "10"

services :
  - docker

cache:
    directories:
      - node_modules/

addons:
  apt:
    packages:
      - docker-ce
  sonarcloud:
    organization: "sonarcloud"

notifications:
  email: false

before_install:
  - sudo service postgresql stop
  - sudo docker-compose up -d
  - sleep 20
  - npm update
  - npm install puppeteer
  - npm install jasmine
  - npm install sonar-scanner@3.1.0

script:
  - curl localhost:3000
  - npm run test
  - sonar-scanner
