version: '3'
services:
  web:
    build: .
    #command: npm run start
    volumes:
       - .:/app/
       - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
  #    DATABASE_URL: postgres://cdpapp@postgres/cdp
#      SEQ_USER: cdp
      DATABASE_URL: postgres://cdp@postgres:5432/docker
      PORT: 3000

  postgres:
    image: postgres:9.6.2-alpine
    volumes:
      - ./src/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=cdp
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=docker
    ports:
      - 5432:5432
